/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--color-bg)',
        surface: 'var(--color-surface)',
        'surface-elevated': 'var(--color-surface-elevated)',
        'surface-overlay': 'var(--color-surface-overlay)',
        border: 'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',
        text: 'var(--color-text)',
        'text-muted': 'var(--color-text-muted)',
        'text-subtle': 'var(--color-text-subtle)',
        accent: 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        'accent-muted': 'var(--accent-muted)',
        status: {
          healthy: 'var(--status-healthy)',
          'healthy-muted': 'var(--status-healthy-muted)',
          degraded: 'var(--status-degraded)',
          'degraded-muted': 'var(--status-degraded-muted)',
          failing: 'var(--status-failing)',
          'failing-muted': 'var(--status-failing-muted)',
          unknown: 'var(--status-unknown)',
          'unknown-muted': 'var(--status-unknown-muted)',
          paused: 'var(--status-paused)',
          'paused-muted': 'var(--status-paused-muted)',
        },
        severity: {
          critical: 'var(--severity-critical)',
          'critical-muted': 'var(--severity-critical-muted)',
          high: 'var(--severity-high)',
          'high-muted': 'var(--severity-high-muted)',
          medium: 'var(--severity-medium)',
          'medium-muted': 'var(--severity-medium-muted)',
          low: 'var(--severity-low)',
          'low-muted': 'var(--severity-low-muted)',
        },
        chart: {
          1: 'var(--chart-1)',
          2: 'var(--chart-2)',
          3: 'var(--chart-3)',
          4: 'var(--chart-4)',
          5: 'var(--chart-5)',
        },
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
    },
  },
  plugins: [],
};
