/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--color-bg)',
        surface: 'var(--color-surface)',
        'surface-elevated': 'var(--color-surface-elevated)',
        'surface-overlay': 'var(--color-surface-overlay)',
        border: 'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',
        hairline: 'var(--hairline)',
        'hairline-strong': 'var(--hairline-strong)',
        text: 'var(--color-text)',
        'text-muted': 'var(--color-text-muted)',
        'text-subtle': 'var(--color-text-subtle)',
        accent: 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        'accent-muted': 'var(--accent-muted)',
        'accent-weak': 'var(--accent-weak)',
        status: {
          healthy: 'var(--status-healthy)',
          'healthy-muted': 'var(--status-healthy-muted)',
          degraded: 'var(--status-degraded)',
          'degraded-muted': 'var(--status-degraded-muted)',
          failing: 'var(--status-failing)',
          'failing-muted': 'var(--status-failing-muted)',
          unknown: 'var(--status-unknown)',
          'unknown-muted': 'var(--status-unknown-muted)',
          paused: 'var(--status-paused)',
          'paused-muted': 'var(--status-paused-muted)',
        },
        severity: {
          critical: 'var(--severity-critical)',
          'critical-muted': 'var(--severity-critical-muted)',
          high: 'var(--severity-high)',
          'high-muted': 'var(--severity-high-muted)',
          medium: 'var(--severity-medium)',
          'medium-muted': 'var(--severity-medium-muted)',
          low: 'var(--severity-low)',
          'low-muted': 'var(--severity-low-muted)',
        },
        chart: {
          1: 'var(--chart-1)',
          2: 'var(--chart-2)',
          3: 'var(--chart-3)',
          4: 'var(--chart-4)',
          5: 'var(--chart-5)',
        },
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        pill: 'var(--radius-pill)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
      backdropBlur: {
        material: '20px',
      },
      backdropSaturate: {
        material: '180%',
      },
      transitionTimingFunction: {
        standard: 'var(--ease-standard)',
        spring: 'var(--ease-spring)',
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        base: 'var(--duration-base)',
        slow: 'var(--duration-slow)',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        'display-sm': ['24px', { lineHeight: '1.15', letterSpacing: '-0.022em' }],
        'display-md': ['32px', { lineHeight: '1.1', letterSpacing: '-0.024em' }],
        'display-lg': ['40px', { lineHeight: '1.08', letterSpacing: '-0.026em' }],
      },
    },
  },
  plugins: [],
};
